base_model: Qwen/Qwen3-4B-Instruct-2507

data:
  train_file: /kaggle/working/ACHMRA/data/achmra/train.jsonl
  val_file: /kaggle/working/ACHMRA/data/achmra/val.jsonl
  test_file: /kaggle/working/ACHMRA/data/achmra/test.jsonl
  preference_file: /kaggle/working/ACHMRA/data/achmra/preference.jsonl
  rl_file: /kaggle/working/ACHMRA/data/achmra/rl.jsonl
  tokenizer_dir: null

sft:
  epochs: 1.5
  learning_rate: 1.5e-4
  batch_size: 32
  gradient_accumulation: 8
  warmup_ratio: 0.05

preference:
  epochs: 1.0
  learning_rate: 1.0e-4
  batch_size: 16
  gradient_accumulation: 16
  warmup_ratio: 0.1

rl:
  epochs: 0.25
  learning_rate: 5.0e-5
  batch_size: 8
  gradient_accumulation: 32
  warmup_ratio: 0.05
  reward_beta: 0.2
  abstain_bonus: 0.4
  incorrect_penalty: 1.5
  length_penalty: 0.1

lora:
  enabled: true
  r: 128
  alpha: 256
  dropout: 0.05
  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    - gate_proj
    - up_proj
    - down_proj

latent_passes:
  control_tokens:
    - <pass_0>
    - <pass_1>
    - <verify>
    - <compress>
  embedding_dim: 96
  loss_weight: 0.6
  encourage_silence_weight: 0.15

internal_language:
  begin_token: <il_begin>
  end_token: <il_end>
  bridge_token: <il_bridge>
  loss_weight: 0.3

thought_graph:
  node_token: <got_node>
  edge_token: <got_edge>
  section_token: <got_section>
  summary_token: "[THOUGHT]"
  loss_weight: 0.45

calibration:
  confidence_token: "[CONF]"
  loss_type: brier
  loss_weight: 1.0
  temperature_scaling: true

anti_cot:
  loss_weight: 0.35
  allowed_tokens:
    - "[THOUGHT]"
    - "[FINAL]"
    - "[CONF]"
    - "[NEXT]"
    - "[IDK]"

curriculum:
  - name: no_pass
    min_passes: 0
    max_passes: 0
    weight: 0.2
  - name: single_pass
    min_passes: 1
    max_passes: 1
    weight: 0.45
  - name: double_pass
    min_passes: 2
    max_passes: 2
    weight: 0.35

max_sequence_length: 4096
trust_remote_code: false
revision: null
gradient_checkpointing: true
load_in_4bit: true
bf16: true
debug_keyword: ACHMRA_DEBUG_TRACE

export:
  output_dir: artifacts/achmra_base_solo
  quantizations:
    - Q6_K
    - Q4_K_M
  gguf_name: ACHMRA-Base-Solo
